version: '3.8'

services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/harddrive/file-browser/data:/srv
      - /mnt/harddrive/file-browser/database:/database
      - /mnt/harddrive/file-browser/config:/config
