services:
  glance:
    container_name: glance
    image: glanceapp/glance
    user: "1000"
    volumes:
      - "/mnt/harddrive/glance:/app/config"
    ports:
      - "8081:8080"
    restart: unless-stopped

