services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/harddrive/nextcloud/config:/config
      - /mnt/harddrive/nextcloud/data:/data
    ports:
      - 4443:443
      - 8089:80
    restart: unless-stopped

