services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /mnt/harddrive/nginx-proxy-manager/data:/data
      - /mnt/harddrive/nginx-proxy-manager/letsencrypt:/etc/letsencrypt

