services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8083:80/tcp"
      - "3445:443/tcp"
    environment:
      TZ: 'Europe/Rome'
      FTLCONF_webserver_api_password: '${PIHOLE_API_PASSWORD}'
      FTLCONF_dns_listeningMode: 'all'
    volumes:
      - /mnt/harddrive/pihole/config:/etc/pihole
      - /mnt/harddrive/pihole/dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
    restart: unless-stopped

